# Runs a single command using the runners shell
name: Example workflow for Python using Snyk 

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: d6c3f088-51cf-4418-9fea-7de78bc07b80
